Dev
unbeman/ya-prac-go-first-grade pull request #1
Opened 2023-05-30 12:28 UTC by unbeman

Разработка системы по ТЗ индивидуального выпускного проекта "Накопительная система лояльности «Гофермарт»".
Сделано:
Регистрация и авторизация пользователя, аутентификация по токену
Добавление заказа загрузкой номера заказа с проверкой по алгоритму Луна
Получение списка заказов, текущего баланса и историю о списании баллов пользователя
Списание и начисление баллов за заказы

Проверка заказа в системе расчета баллов лояльности происходит при запросе на получение списка заказов
(в данный момент в синхронном режиме)

TODO:
Проверять заказы в системе расчета баллов в асинхронном режиме в момент запроса пользователя на получение списка заказов
Обернуть БД запросы чтобы не торчали в контроллере (нарушение слоев)
Протащить контекст и назначить таймауты

2023-05-31 21:33 UTC, tmvrus requested changes
- закомментированный код засоряет проект и усложняет его чтение, рекомендую избегать
- рекомендую заново ознакомиться в темой контекстов
- так же следует пересмотреть конструкцию
```
func (h AppHandler) xxxx() http.HandlerFunc {
	return func(writer http.ResponseWriter, request *http.Request) {}
```
она полностью бессмысленна в контексте данного приложения и ее можно без потерь заменить на 
```
func (h AppHandler) xxxx(writer http.ResponseWriter, request *http.Request) 
```
- нет ни одного теста

2023-05-31 21:33 UTC, tmvrus commented on cmd/gophermart/main.go
> +	}()
какой смысл в WithCancel если он отменяется только в defer?

2023-05-31 21:33 UTC, tmvrus commented on cmd/gophermart/main.go
> +		}
цикл тут не нужен, приложение ведь можно остановить только один раз?

2023-05-31 21:33 UTC, tmvrus commented on internal/app/app.go
> +	workerPool := worker.NewWorkersPool(3)
скрытый смысл цифры 3 понятен только автору кода, если бы нее месте была именованная константа, то это улучшило бы читаемость

2023-05-31 21:33 UTC, tmvrus commented on internal/connection/accrual.go
> +	defer cancel()
зачем понадобилось ctx2? почему нельзя использовать ctx?

2023-05-31 21:33 UTC, tmvrus commented on internal/connection/accrual.go
> +		defer response.Body.Close()
тело может быть и при статусе отличном от StatusOK

2023-05-31 21:33 UTC, tmvrus commented on internal/connection/accrual.go
> +		request.Header.Get("Retry-After")
это требование должно быть реализовано явно

2023-05-31 21:33 UTC, tmvrus commented on internal/controller/points.go
> +	errors2 "github.com/unbeman/ya-prac-go-first-grade/internal/apperrors"
это прям пример безобразного неймигна

2023-05-31 21:33 UTC, tmvrus commented on internal/controller/points.go
> +}
зачем вообще этот метод если он всегда возвращает одно и то же

2023-05-31 21:33 UTC, tmvrus commented on internal/worker/workers.go
> +}
запись nil-error в канал для ошибок выглядит как непродуманный дизайн

2023-05-31 21:33 UTC, tmvrus commented on internal/database/db.go
> +	})
что мешает трем транзакциям вычитать одновременно 
```
tx.Where("id = ? and current_balance >= ?", user.ID, withdrawInfo.Sum).First(user)
```
затем по очереди сделать update/create и убрать баланс в минус?

2023-05-31 21:34 UTC, tmvrus requested changes
- закомментированный код засоряет проект и усложняет его чтение, рекомендую избегать
- рекомендую заново ознакомиться в темой контекстов
- так же следует пересмотреть конструкцию
```
func (h AppHandler) xxxx() http.HandlerFunc {
	return func(writer http.ResponseWriter, request *http.Request) {}
```
она полностью бессмысленна в контексте данного приложения и ее можно без потерь заменить на 
```
func (h AppHandler) xxxx(writer http.ResponseWriter, request *http.Request) 
```
- нет ни одного теста

2023-06-01 20:58 UTC, unbeman commented on internal/connection/accrual.go
> +	defer cancel()
Он назначает таймаут запроса
Но с учетом того что у нас только один запрос и уже есть назначенный таймаут для клиента, он тут избыточен.

2023-06-02 19:34 UTC, unbeman commented on internal/connection/accrual.go
> +		request.Header.Get("Retry-After")
@tmvrus сейчас обновление заказа происходит асинхронно в момент запроса. Если сервис расчета баллов не смог ответить со статусом `OK`, то отдаем пользователю старую информацию по заказу.
Можно переделать логику управления обновления заказов так:
При успешной регистрации нового заказа (и при рестарте сервера для всех не рассчитанных заказов) раз в какое-то время запрашивать у сервиса расчета баллов информацию о начислениях до тех пор, пока не получим желаемый статус заказа (PROCESSED или INVALID), если получили статус ответа `TooManyRequests` - спим заданное в хэдере `Retry-After` секунд и снова запрашиваем информацию
При таком подходе время ответа пользователю будет заметно ниже, но возрастет нагрузка на сервисы

2023-06-02 20:20 UTC, unbeman commented on internal/connection/accrual.go
> +		request.Header.Get("Retry-After")
@tmvrus является ли статус ответа сервиса расчета баллов лояльности `204 - NoContent` конечным?
Или возможно что он сменится на `200 - OK` в будущем?

2023-06-02 21:42 UTC, unbeman commented on internal/connection/accrual.go
> +		request.Header.Get("Retry-After")
>сейчас обновление заказа происходит асинхронно в момент запроса. Если сервис расчета баллов не смог ответить со статусом OK, то отдаем пользователю старую информацию по заказу.

Еще подумала, что можно так и оставить, но назначить таймаут для обновления заказов пользователя через контекст. В случае если сервис расчета отдал статус `500` - спим и пробуем еще раз, если `429` - спим по `Retry-After` и пробуем еще раз. Если не укладываемся в заданный таймаут или статус - `204`, то отдаем старое значение заказа

2023-06-05 13:45 UTC, tmvrus commented on internal/connection/accrual.go
> +		request.Header.Get("Retry-After")
Если сервис отдает 429 он ожидает что клиент изменит свое поведение в связи с этим, в данном случае нет никакого изменения - есть только todo

2023-06-06 09:25 UTC, tmvrus approved these changes

2023-06-06 15:48 UTC, merged